CREATE USER C##QL IDENTIFIED BY midnightheaven;

-- USER SQL
ALTER USER "C##QL"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER "C##QL" QUOTA UNLIMITED ON "USERS";
-- ROLES
GRANT "CONNECT" TO "C##QL" ;
GRANT "RESOURCE" TO "C##QL" ;

-- SYSTEM PRIVILEGES
GRANT CREATE SESSION TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE ANY INDEX TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "C##QL" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "C##QL" WITH ADMIN OPTION;

GRANT SELECT ANY SEQUENCE TO "C##QL" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY SEQUENCE TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE PROFILE TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER PROFILE TO "C##QL" WITH ADMIN OPTION;
GRANT DROP PROFILE TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE ANY PROCEDURE TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY PROCEDURE TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO "C##QL" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO "C##QL" WITH ADMIN OPTION;

GRANt CREATE ANY VIEW TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE USER TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER USER TO "C##QL" WITH ADMIN OPTION;
GRANT DROP USER TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE ROLE TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO "C##QL" WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO "C##QL" WITH ADMIN OPTION;

GRANT CREATE ANY TRIGGER TO "C##QL" WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO "C##QL" WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO "C##QL" WITH ADMIN OPTION;

GRANT SELECT ANY TRANSACTION TO "C##QL" WITH ADMIN OPTION;


